---

- hosts: all
  become: true
  tasks:

  - name: install & update apache2 and php packages for Ubuntu
    tags: always
    package:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes

