---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 and php packages for Ubuntu
    apt:
      name: 
        - apache2
      state: latest
